language: node_js

node_js:
  - 12

addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci

env:
  - RECORD_KEY=b98cff40-8555-40e4-982b-5af09efaabd4

defaults: &defaults
  script:
    - npm run cy:travis -- --record --key $RECORD_KEY --parallel --group $STAGE_NAME --ci-build-id $STAGE_NAME-$TRAVIS_BUILD_ID --browser $BROWSER
    - kill $(jobs -p) || true

jobs:
  include:
    - stage: test
      env:
        - STAGE_NAME="1x-electron"
        - BROWSER="electron"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="2x-chrome"
        - BROWSER="chrome"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="2x-chrome"
        - BROWSER="chrome"
      <<: *defaults