# language: node_js

# node_js:
#   - 12

# addons:
#   apt:
#     packages:
#     - libgconf-2-4

# cache:
#   directories:
#     - ~/.npm
#     - ~/.cache
#   override:
#     - npm ci

# script:
#   - npm run cy:debug
#   - kill $(jobs -p) || true

language: node_js

node_js:
  - 12

addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci

defaults: &defaults
  script:
    - npm run cy:debug -- --record --key b98cff40-8555-40e4-982b-5af09efaabd4 --parallel --group $STAGE_NAME
    - kill $(jobs -p) || true

jobs:
  include:
    - stage: "1st thread"
      env:
        - STAGE_NAME="2x-electron"
      <<: *defaults
    - stage: "2nd thread"
      env:
        - STAGE_NAME="2x-electron"
      <<: *defaults
