language: node_js

node_js:
  - 12

addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci

script:
  - npm run cy:run:docker
  - kill $(jobs -p) || true