language: node_js

node_js:
  - 12

addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci

script:
  - npm run cy:run:docker -- --record --key b98cff40-8555-40e4-982b-5af09efaabd4
  - kill $(jobs -p) || true