# name: Cypress Tests using Cypress Docker Image

# on: [push]

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     container: cypress/browsers:node12.18.3-chrome87-ff82
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Cypress run
#         uses: cypress-io/github-action@v2
#         with:
#           record: true
#           browser: chrome
#           start: npm run
#         env:
#           CYPRESS_RECORD_KEY: b98cff40-8555-40e4-982b-5af09efaabd4

name: Cypress Tests using Cypress Docker Image

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        uses: docker build -t cypress-demo .

      - name: Run tests
        run: docker-compose up